### ISSUE TITLE
pending request or 408 request timeout

### ISSUE THREAD

**Issue by RodeoAdrian** [meabed/graphql-upload-ts#131] opened 2023-04-11 20:00 UTC
I can't make this package work.
Node v18.15
graphql-upload-ts v2.0.5
@apollo/server v4.5.0

```javascript
import express from 'express';
import { createServer } from 'http';
import cors from 'cors';
import { ApolloServer } from '@apollo/server';
import { expressMiddleware } from '@apollo/server/express4';
import { ApolloServerPluginDrainHttpServer } from '@apollo/server/plugin/drainHttpServer';
const { graphqlUploadExpress } = require('graphql-upload-ts');

async function applyMiddlewares(app, httpServer) {
  app.use(morganMiddleware);
  app.use(bugsnagMiddleware.requestHandler);
  app.use('*', (req, res, next) => {
    logger.info(`Request Origin - ${req.protocol}://${req.get('host')}`);
    next();
  });
  app.use('*', cors(corsOptionsDelegate));
  app.use(bugsnagMiddleware.errorHandler);
  app.use(express.urlencoded({ extended: true }));
  app.use(express.json());

  apolloSchema.plugins = [ApolloServerPluginDrainHttpServer({ httpServer })];
  apolloSchema.allowBatchedHttpRequests = true;
  const apolloServer = new ApolloServer(apolloSchema);
  await apolloServer.start();

  app.use(
    '/graphql',
    graphqlUploadExpress(),
    expressMiddleware(apolloServer, {
      context: async ({ req }) => contextFnInjections(req)
    })
  );
}

async function initServer() {
  initializeNewRelic();
  const app = express();
  const httpServer = createServer(app);
  await applyMiddlewares(app, httpServer);
  bindRestRoutes(app);

  return httpServer;
}

export default initServer;
```

Queries and mutations work, but not the file uploads.

![Screenshot 2023-04-11 at 16 57 47](https://user-images.githubusercontent.com/97752751/231275062-48987732-6653-4219-9739-dc783d91354f.png)

**Comment by HoangDevNull** [comment] 2023-08-08 06:40
Any fix for this ? I have the same problem.

**Comment by vorlov** [comment] 2023-09-19 13:59
me too

**Comment by meabed** [comment] 2023-09-19 15:34
Could you pass the option and try
``` 
graphqlUploadExpress({overrideSendResponse: false})
```

**Comment by DHFW** [comment] 2024-01-10 11:18
@meabed I also have this issue for larger files (like PDF's of 600kb). When I use a 2kb PNG file, my mutation with file1, file2 works flawlessly. However, when I upload two different PDF files, I see when console logging the input that the first file1 is a promise with some data, the second file is indicating that it is a pending promise. After that, the process just does nothing anymore and ultimately is a request timeout.

I tried setting the maxFileSize to 10_000_000, and maxFiles: 3. I tried overrideSendResponse: false and true, both are not working.
```javascript
file1: Promise {
    {
      fieldName: '1',
      filename: 'somefile.pdf',
      mimetype: 'application/pdf',
      encoding: '7bit',
      createReadStream: [Function: createReadStream]
    },
    [Symbol(async_id_symbol)]: 658,
    [Symbol(trigger_async_id_symbol)]: 654
  },
  file2: Promise {
    <pending>,
    [Symbol(async_id_symbol)]: 660,
    [Symbol(trigger_async_id_symbol)]: 654
  }
```

**Comment by DHFW** [comment] 2024-01-12 08:56
@meabed I was able to make it work! 

What I did was based on your repository source files copy all the files in my local project. Then, I replaced the following files from the latest version of the `graphql-upload` repo (16.0.2):

`GraphQLUpload`
`graphqlUploadExpress`
`processRequest`

To make it work/compile in my TypeScript project I added a bunch of types or just ignored the types for now. I had to add a couple of dependencies:
```json
"busboy": "^1.6.0",
"fs-capacitor": "^8.0.0"
```
Dev deps:
```json
"@types/busboy": "^1.5.3",
"@types/object-path": "^0.11.4"
```

I could not use the `graphql-upload` normal dependency because it has requirements for my TypeScript setup that are not feasible (unfortunately) (too many changes required).

I can not exactly pinpoint what made the difference, but the pending promise of the second file is the culprit. I think the main difference is the capacitor setup in the `processRequest` in the `graphql-upload` repo. If you (or someone else) can look at that it would be very helpful! I've lost so much time already by researching and trying different packages `graphql-upload-minimal` has the same issue as this package, which make sense since you have based if off of that I guess`. I hope I can help others with these remarks.

**Comment by meabed** [comment] 2024-01-12 11:26
Thank you @DHFW will look at this today and fix it 😊

**Comment by meabed** [comment] 2024-01-15 13:19
Thank you @RodeoAdrian @DHFW 

I have added Apollo example here : https://github.com/meabed/graphql-upload-ts/tree/develop/examples/apollo

Could you give a try and let me know if it works or if you have an issue how to reproduce it with this example?

**Comment by meabed** [comment] 2024-01-15 13:22
@DHFW I have tested with files larger than 20mb and it works fine. 

Could you share reproducible code and file for this issue?

**Closed** 2024-02-13 19:21 UTC
