### ISSUE TITLE
Throw error not working

### ISSUE THREAD

**Issue by jinyang1994** [meabed/graphql-upload-ts#78] opened 2022-12-09 08:48 UTC
When an exception is thrown, there is no way to return to the client

```
import { ApolloError } from 'apollo-server-core'

const resolvers: Resolvers = {
  Upload: GraphQLUpload,
  Mutation: {
    async upload(_, { file }) {
      throw new ApolloError('error') // not working
    }
  }
}

export default resolvers
```

![image](https://user-images.githubusercontent.com/15340367/206661797-52741458-57a6-41ce-bd6d-b9fee81a58f4.png)

client version

* "@apollo/client": "^3.7.0",
* "apollo-upload-client": "^17.0.0",

server version

* "apollo-server-core": "^3.9.0",
* "apollo-server-koa": "^3.9.0",
* "graphql-upload-ts": "^2.0.3",

**Comment by meabed** [comment] 2022-12-09 18:26
Thank you @jinyang1994 would you be able to open a PR with the proposed fix?

**Comment by jinyang1994** [comment] 2022-12-10 05:15
> Thank you @jinyang1994 would you be able to open a PR with the proposed fix?

Sorry I don't know how to fix it

**Comment by meabed** [comment] 2022-12-10 19:46
Got it, sure I will have a look

**Comment by jinyang1994** [comment] 2022-12-11 03:14
Thanks

**Comment by meabed** [comment] 2022-12-27 14:05
@jinyang1994 Would you be able to make codesanbox with the code to test it?

Thank you

**Comment by piotr-pawlowski** [comment] 2023-01-05 15:32
It's a problem with `graphql-upload-minimal` lib. Throwing error doesn't work there.

**Comment by meabed** [comment] 2023-01-05 15:46
@piotr-pawlowski thank you - does it work in this implementation?

**Comment by piotr-pawlowski** [comment] 2023-01-05 16:48
@meabed unfortunately your implementation doens't work as well. Throwing error doesn't work - request hangs forever.

**Comment by meabed** [comment] 2023-01-05 16:52
Got it, thank you @piotr-pawlowski 

Would you be able to share code sandbox with the issue so I could fix.

**Comment by jantoine1** [comment] 2023-11-22 22:50
This is easily reproducible using the official graphql-upload-examples repository as a starting point: https://github.com/jaydenseric/apollo-upload-examples. Uploading a file larger than 10MB outputs an error to the terminal.

Here is a fork with the minimal necessary changes to reproduce the issue: https://github.com/jantoine1/apollo-upload-examples. Uploading a file larger than 10MB hangs.

I've also created a cod esandbox here (note that I've never used code sandbox before): https://codesandbox.io/p/github/jantoine1/apollo-upload-examples/master?workspaceId=5a39add2-0200-4244-877c-f9b17c6d7b7e&file=%2F.editorconfig

**Comment by meabed** [comment] 2023-11-22 23:24
Thank you @jantoine1 i will look into it and fix it.
Appreciate the effort

**Comment by meabed** [comment] 2024-01-15 13:30
Thank you @jantoine1 

I have added Apollo example here : https://github.com/meabed/graphql-upload-ts/tree/develop/examples/apollo

Could you give a try and let me know if it works or if you have an issue how to reproduce it with this example?

I have tested with files larger than 20mb and it works fine. 

```
{
  "data": {
    "uploadFile": {
      "uri": "/Users/meabed/workspace/graphql-upload-ts/examples/apollo/dist/examples/apollo/uploaded-1705325159941-2.pdf",
      "filename": "2.pdf",
      "mimetype": "application/pdf",
      "encoding": "7bit",
      "fileSize": 26676280
    }
  }
}
```

<img width="1667" alt="image" src="https://github.com/meabed/graphql-upload-ts/assets/45731/01c301d0-2d39-4280-94da-41b9fdd27835">

**Comment by solanamonk** [comment] 2024-02-13 19:16
I encountered this issue when trying to use graph-upload-ts and ValidationPipe in the same app, because ValidationPipe depends on throwing an exception when there's a validation error in the input.

It seems like when an exception is thrown, streams don’t get closed properly. I "fixed" it in my app by forcibly closing the streams in the exceptionFactory function.

I’m really looking forward to a proper fix.

**Comment by meabed** [comment] 2024-02-13 19:21
@solanamonk could share a code sandbox of the issue?

**Comment by solanamonk** [comment] 2024-02-13 21:23
@meabed I've created a repo with a sample app https://github.com/solanamonk/validation_pipe_with_graphql_upload

The app allows to upload plain text files and increments the upload counter. If a file of another type is uploaded, it should respond with 400 Bad Request. It only works with my awkward custom pipe. If you use ValidationPipe in main.ts instead, it hangs. ValidationPipe throws an exception [here](https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L144)

Here are some one-liners to interact with the API

```bash
curl -X POST 'http://localhost:3000/graphql' -H 'Content-Type: multipart/form-data' -H 'x-apollo-operation-name: incrementUploadCounter' -F 'operations={"query":"mutation ($file: Upload!) { incrementUploadCounter(incrementUploadCounter: { file: $file }) { count } }", "variables": { "file": null }}' -F 'map={"0":["variables.file"]}' -F '0=@/path/to/image.jpeg'
```

```bash
curl -X POST -H "Content-Type: application/json" --data '{ "query": "{ uploadCounter { count } }" }' http://localhost:3000/graphql
```

**Comment by moroale93** [comment] 2024-02-13 23:25
I'm having the same issue on a production app.

**Comment by meabed** [comment] 2024-02-13 23:26
Thank goodness @solanamonk I will check this and see the fix

**Comment by meabed** [comment] 2024-02-14 03:35
This is NestJS issue.... 

@solanamonk could you try this option


```

  app.use(graphqlUploadExpress({
    overrideSendResponse: false
  }));

```

**Comment by meabed** [comment] 2024-02-14 03:38
@moroale93 can you try the same - if its still exist please send a codesandbox

**Comment by moroale93** [comment] 2024-02-14 06:30
@meabed already tried that 😞it doesn't solve the issue.

**Comment by solanamonk** [comment] 2024-02-14 07:00
@meabed Thank you! That option worked for my cause! :heart:

**Comment by moroale93** [comment] 2024-02-14 08:47
@meabed here https://github.com/moroale93/upload-gql I've uploaded an example to see the problem. Here there are 2 packages. The GQL server and the frontend app. On readme you'll find the commands to start both. on frontend app you can select an image file and then press the button to send it. you'll see that the request will stay pending even if the GQL resolver immediatly throws an error.

**Comment by moroale93** [comment] 2024-02-14 09:31
didn't have time to test it @meabed the code is to just give you an idea of the thing ... later this evening I'll give it a check. I'm sorry

**Comment by moroale93** [comment] 2024-02-15 08:33
@meabed it is still pending also while sending a success response. 
Uploaded a new version. If you select a file from the app it sends it as multipart so your middleware gets executed. In that case, the resolver returns an object and should make the mutation work, but it's not.
if you don't select a file, it's sent as JSON and in that case it all work.

**Comment by moroale93** [comment] 2024-02-15 20:13
I think it's something inside the processRequest function. Because if I mock that with the following function, it's successfully handled.
```
processRequest: () =>
            Promise.resolve({
              operationName: 'CreateUser',
              variables: {
                input: {
                  field: 'hello',
                  file: {
                    resolve: () => null,
                    reject: () => null,
                    promise: Promise.resolve({
                      fieldName: '1',
                      filename: 'scorecard example.png',
                      mimetype: 'image/png',
                      encoding: '7bit',
                      createReadStream: () => null,
                    }),
                    file: {
                      fieldName: '1',
                      filename: 'scorecard example.png',
                      mimetype: 'image/png',
                      encoding: '7bit',
                      createReadStream: () => null,
                    },
                  },
                },
              },
              query:
                'mutation CreateUser($input: CreateMeInput!) {\n' +
                '  createMe(input: $input) {\n' +
                '    field\n' +
                '    __typename\n' +
                '  }\n' +
                '}',
            }),
```

**Comment by moroale93** [comment] 2024-02-18 08:40
@meabed is it possible that the response object gets rewritten and so the `res.send` has no effect? or in case, are some headers uncorrectly set?

**Comment by meabed** [comment] 2024-02-20 05:34
@moroale93 the client you have sending application/json on file upload because apollo client doesnt support it - https://www.apollographql.com/docs/react/data/file-uploads/

you would most likely need to try to use this package apollo-upload-client

**Comment by moroale93** [comment] 2024-02-20 06:34
> you would most likely need to try to use this package apollo-upload-client

I am already using it.
And that's exactly how it works on my example.

**Comment by meabed** [comment] 2024-02-20 06:38
@moroale93 when I tried the code you have there it was sending json, could you make it send multipart form so I could look at it

**Comment by moroale93** [comment] 2024-02-20 06:43
it is sending multipart if you select a file frontend e front, pull it again 😊 

PS: 
the graphqlUploadExpress.js file shows an example of usage, but that's not the [offical way to use graphql with express](https://www.apollographql.com/docs/apollo-server/api/express-middleware#example).
```js
  const express = require('express');
  const graphqlHTTP = require('express-graphql');
  const { graphqlUploadExpress } = require('graphql-upload-minimal');
  const schema = require('./schema');
 
  express()
    .use(
      '/graphql',
      graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }),
      graphqlHTTP({ schema })
    )
    .listen(3000);
```

**Comment by meabed** [comment] 2024-02-20 07:06
@moroale93 i selected a file through the frontend and it was not sending multipart request

Can u reproduce with bash curl as I have in the examples

**Comment by meabed** [comment] 2024-02-21 15:08
@moroale93 I dis small changes and tested with curl upload and it works fire ✅ 

<img width="566" alt="image" src="https://github.com/meabed/graphql-upload-ts/assets/45731/1911aa4d-16e6-43df-a633-dc3387f9076a">

<img width="1309" alt="image" src="https://github.com/meabed/graphql-upload-ts/assets/45731/ed788d97-4758-4f28-a9a9-50fdac5edb9e">

<img width="654" alt="image" src="https://github.com/meabed/graphql-upload-ts/assets/45731/c85155d6-ee25-422b-9e0e-d7743d2c4146">


```
#!/bin/bash

# upload.sh
# Usage: ./upload.sh http://localhost:4000/graphql test.png
# Usage: ./upload.sh http://localhost:4000/graphql test.jpg

curl -v -L $1 \
  -H 'x-apollo-operation-name: CreateUser' \
  -H 'Apollo-Require-Preflight: true' \
  -F operations='{ "query": "mutation ($file: Upload!) { createMe(file: $file) { field  } }", "variables": { "file": null } }' \
  -F map='{ "0": ["variables.file"] }' \
  -F 0=@$2
```

There is something wrong in the frontend client it doesnt send multipart form upload

**Comment by solanamonk** [comment] 2024-02-21 22:33
@meabed I'm afraid you might have closed it too early, it turns out it hangs on two binary uploads.

I added change to my repository to reproduce https://github.com/solanamonk/validation_pipe_with_graphql_upload

2 text uploads, ok:
```bash
curl -X POST 'http://localhost:3000/graphql' -H 'Content-Type: multipart/form-data' -H 'x-apollo-operation-name: incrementUploadCounter' -F 'operations={"query":"mutation ($file: Upload, $file2: Upload) { incrementUploadCounter(incrementUploadCounter: { file: $file, file2: $file2 }) { count } }", "variables": { "file": null, "file2": null }}' -F 'map={"0":["variables.file"],"1":["variables.file2"]}' -F '0=@/path/to/file.txt' -F '1=@/path/to/file2.txt'
```

1 binary upload, ok (responds with a validation error):
```bash
curl -X POST 'http://localhost:3000/graphql' -H 'Content-Type: multipart/form-data' -H 'x-apollo-operation-name: incrementUploadCounter' -F 'operations={"query":"mutation ($file: Upload) { incrementUploadCounter(incrementUploadCounter: { file: $file }) { count } }", "variables": { "file": null }}' -F 'map={"0":["variables.file"]}' -F '0=@/path/to/file.jpeg'
```

2 binary uploads, hangs:
```bash
curl -X POST 'http://localhost:3000/graphql' -H 'Content-Type: multipart/form-data' -H 'x-apollo-operation-name: incrementUploadCounter' -F 'operations={"query":"mutation ($file: Upload, $file2: Upload) { incrementUploadCounter(incrementUploadCounter: { file: $file, file2: $file2 }) { count } }", "variables": { "file": null, "file2": null }}' -F 'map={"0":["variables.file"],"1":["variables.file2"]}' -F '0=@/path/to/file.jpeg' -F '1=@/path/to/file2.jpeg'
```

**Comment by codeholic** [comment] 2024-02-21 22:41
Oh, wait. It seems it doesn't have anything to do whether the file is binary or not, but with the size of files. I just took two JPEG files of 125 bytes, and it worked.

**Comment by meabed** [comment] 2024-02-21 22:46
I will have a look, but I tried with large file too and it works fine.

**Comment by meabed** [comment] 2024-02-21 22:53
@codeholic can u make repo with the exact error and file size ?

**Comment by meabed** [comment] 2024-02-21 22:54
@solanamonk i will check this example

**Comment by codeholic** [comment] 2024-02-21 23:06
@meabed Have you tried two large files? I've added images I could reproduce the issue with, to the repository.

There is no error, it just hangs (the validation error I mentioned above is fine, because it's intended by the app logic)

**Comment by solanamonk** [comment] 2024-02-21 23:09
@meabed Sorry for the mess I did here, @codeholic and me is the same person :D

**Comment by meabed** [comment] 2024-02-21 23:15
@solanamonk could you organise the repo in way to reproduce the issue directly please

**Comment by solanamonk** [comment] 2024-02-21 23:24
@meabed it is right here https://github.com/solanamonk/validation_pipe_with_graphql_upload

```bash
npm install
npm run start:dev
```

then run

```bash
curl -X POST 'http://localhost:3000/graphql' -H 'Content-Type: multipart/form-data' -H 'x-apollo-operation-name: incrementUploadCounter' -F 'operations={"query":"mutation ($file: Upload, $file2: Upload) { incrementUploadCounter(incrementUploadCounter: { file: $file, file2: $file2 }) { count } }", "variables": { "file": null, "file2": null }}' -F 'map={"0":["variables.file"],"1":["variables.file2"]}' -F '0=@2814.png' -F '1=@6127.png'
```

**Comment by meabed** [comment] 2024-02-22 06:56
@solanamonk I got the issue - and working to fix it.

**Comment by meabed** [comment] 2024-02-22 08:37
@moroale93 could you try the best this version 2.1.1-beta.42

**Comment by solanamonk** [comment] 2024-02-22 09:30
@meabed Thank you for a prompt fix, that worked like a charm for me! :heart: Would you mind to explain shortly what the issue was so I can learn something today? :smile:

**Comment by meabed** [comment] 2024-02-23 17:04
The upload file stream was hanging or stuck because its multipart upload ( first part or chunk ) was not consumed with stream.on('data'=>{}) - so it won't progress to upload second chunk of the upload! 

So the stream had to be reworked a bit to allow all the multipart upload to be sent and then pipeline new streams to graphql resolver.


I will release this fixes shortly today.

**Closed** 2024-02-24 03:14 UTC

**Comment by jguzej** [comment] 2024-04-27 08:58
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
nigel-hall-codes, @520lly, @manson-1, @mmagu, @zzl0, @knabben, @hallo-w3lt, @bitnitdit, @nio-p, @Dudu-Lucky, @victorusachev, @hygtjm, @micweaver, @cutamar, @yfhk, @imclint21, @xiaotan, @robzhang, @stone99, @0xhari, @AyeMoet, @arlind9999, @steve-taylor, @Kokkomaki, @jessemarco, @RobespierreXu, @prestontighe, @vicvon, @sekmet, @meiqi1992, @aoooio, @Himujjal, @BaofengWu, @Noobi99, @kyuty, @tudela, @Tobue, @mr-pinzhang, @zqzjz0911, @incidunt, @fanjieqi, @OfekTap, @mehl321, @zhou-, @mylovemoo, @IsSt1cker, @htaozhang, @gitmax1992, @dricetar, @teamritzhangyangyu, @Strongtheory, @KnightHJ, @Utley, @d-cifer, @jroller03, @adwardlee, @WilleamZhao, @pedro823, @nicett, @aakarsh, @robbenmu, @nguyenpc, @frudder, @vsn4ik, @RigoOnRails, @celestegerard, @dvasiliauskas, @mugartec, @indidatajones, @vedard, @thinkbox, @emilianopenedo, @luc-lynx, @bidva, @ahalekelly, @JasonYangShadow, @hayscoding, @robertchase05, @tugayevci, @anirudh-chhangani, @thepkbadger, @yg-x, @Vic-Li, @wannabit-jayb, @logest, @chatender, @oakaigh, @lancemayer, @inyoungcome, @xiaoxuanzi, @deralation, @davidbroza, @freew01f, @s1mpletru1h, @luzhongzhou, @regnarock, @gosuhiman, @amstrongmartins, @wlMalktkuebler, @Sagar133, @ahmadpx, @oslvbo, @wanpeng, @fed-franz, @milesxu, @sander-m, @k0k0b34n, @devynnpalmer, @KPhilly, @chanhosuh, @xuhongfei, @hellospringo, @ajaxwang, @arkeros, @einelefantle, @kivenZheng, @kkpan11, @Um1Nek0, @pvwzh, @mtrstudio, @gaogle, @msdkinn, @josh-kean, @elonmusx, @dnlowman, @gregszero, @bas, @AluBhorta, @MaxPleaner, @BestByte, @vareshd, @Yohann-Chen, @Ron89, @bitQ2019, @maxgfr, @03968, @flpms, @Honglei-Cong, @0xlitf, @cy920820, @1-am-r00t, @graysign, @guantingz, @XXUeo, @haguo, @sakalauskas, @coshinen, @NineDfishj2cms, @Mawco, @MasatoraAtarashi, @nikolobok, @CraigChilds94, @jdubbya, @cdbBinary, @wall-u, @VKingi, @imfantuan, @kichul1122, @boyujuxiu, @ziishaned, @AndreiShybin, @aotou, @missingmeow, @syednaemx, @sourcesoft, @ygz012, @FishingKingczj, @relue2718, @PocketNinja-io, @xiaobudongzhang, @jwoolf, @Luvgordon, @manbyt, @ianchan0817, @geocfu, @inpay, @lntoly, @MarkHoo, @Linkea, @spcooney, @mikeaxle, @muchenshou, @christinecxm, @pavelleiman, @redatom, @seevali, @chengwei20, @entire, @okayz, @DreamerDyh, @behfar, @kieran-github, @yiyanwannian, @xuehaobiancheng, @zerfew, @meabed, @Richie78321vielhuber, @Perfect404, @salisbury-espinosa, @jensneuhaus, @AlirezaAbdiyan, @calvincoxiii, @NicoKM, @lunzueta, @THOTH432, @zongbingwang, @jonas-pietzsch, @LongshotTony, @jwc1zkj, @chakery, @htornado, @minkikim89, @Fyume, @okzhu, @sheng9527, @pairxj, @rainkeyshen, @zmwilliam, @gemon297, @cunsalan, @luleilei516, @rypalmer, @verretor, @fukua95, @horse304, @alediazusa, @helton, @ashokpeeta, @jaredchu, @mrslvr1346, @yeyian, @daouzo, @cyprianos, @xanbots, @eos21, @bugwars, @fars, @renzo-blockchain, @solon1, @sanjitjain2, @TheDayAfterSaturday, @miwest929, @pmeiyu, @yinengy, @itsnotvalid, @ckwenroninro, @JoshuaMichaelKing, @Licoricewo, @frankjardel, @FabiGjuzi, @mm99inos, @motocarota, @ctyar, @K68, @andresberejnoi, @loseheaven, @techperfect, @JimWongM, @tmael, @More-decentral, @mrldroid, @giancarloGiuffra, @xiaopeifeng, @adityadhiman12, @AmriSulaiman78, @fidelisrafael, @sffernando, @Jobeso, @leoyoung07, @ck0379, @gouchy, @photogaff, @daniellucasss, @sidman2, @SimonBiggs, @zwyzzu, @baoziv587, @hxrain, @ali-master, @kengonakajima, @pizheng, @fr0nky0ng, @Jaaaaaay, @ob1y2k, @nekolunar, @svanstaa, @gaoshanliushui662, @rain7fine11, @Z33DD, @TowerKing, @x5engine, @daiyu, @xorob0, @AndreySupryaga, @wjybluselpcz, @montecarlo1, @Freccia, @BuGoNee, @dbaspider, @zp0605, @yishuaidu, @guiness333, @mezod, @dlajarretie, @mihailovmk, @urugang, @wkrdixon, @yssharma, @myd7349, @Sqlver, @tiaanduplessis, @sirakuz, @andreud, @drgomesp, @xiyanxiyan11, @walkertop, @isopen, @stevenup, @eqqlyz, @joshrowley, @008b8b, @JeremyCrookshank, @DhunterAO, @kncogic, @BubiJonah, @mxc04mc0, @ihuangqi, @darshil, @iplaymore, @widegren, @Gab0, @will123195, @evanlabs, @farolfo, @KarimJedda, @tahtaciburak, @ThomasMDavis, @CblPOKOT, @Allfast7, @shaunstanislauslau, @zekizeki, @liulqing, @wjohnson07, @nitrek
